superhero_database/superhero_database/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_database/superheroes/urls.py
from django.urls import path
from . import views


app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:superhero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create_new_superhero'),
    path('update/<int:superhero_id>/', views.update, name='update_superhero'),
    path('delete/<int:superhero_id>/', views.delete, name='delete_superhero')
]

superhero_database/superheroes/models.py
from django.db import models


# Create your models here.
class Superhero(models.Model):
    superhero_name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catchphrase = models.CharField(max_length=50)

    def __str__(self):
        return self.superhero_name

superhero_database/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Superhero
from django.urls import reverse


# Create your views here.
def index(request):
    all_superheroes = Superhero.objects.all()
    context = {
        'all_superheroes': all_superheroes
    }
    return render(request, 'superheroes/index.html', context)


def create(request):
    if request.method == 'POST':
        superhero_name = request.POST.get('superhero_name')
        alter_ego = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary_ability')
        secondary_ability = request.POST.get('secondary_ability')
        catchphrase = request.POST.get('catchphrase')
        new_superhero = Superhero(superhero_name=superhero_name, alter_ego=alter_ego,
                                  primary_ability=primary_ability, secondary_ability=secondary_ability,
                                  catchphrase=catchphrase)
        new_superhero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')


def detail(request, superhero_id):
    single_superhero = Superhero.objects.get(pk=superhero_id)
    context = {
        'single_superhero': single_superhero
    }
    return render(request, 'superheroes/detail.html', context)


def update(request, superhero_id):
    if request.method == 'POST':
        updated_hero = Superhero.objects.get(pk=superhero_id)
        updated_hero.superhero_name = request.POST.get('superhero_name')
        updated_hero.alter_ego = request.POST.get('alter_ego')
        updated_hero.primary_ability = request.POST.get('primary_ability')
        updated_hero.secondary_ability = request.POST.get('secondary_ability')
        updated_hero.catchphrase = request.POST.get('catchphrase')
        updated_hero.save()
        return detail(request, superhero_id)
    else:
        superhero = Superhero.objects.get(pk=superhero_id)
        context = {
            'superhero': superhero
        }
        return render(request, 'superheroes/update.html', context)


def delete(request, superhero_id):
    Superhero.objects.filter(pk=superhero_id).delete()
    return HttpResponseRedirect(reverse('superheroes:index'))

superhero_database/superheroes/templates/superheroes/create.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Superhero Creation</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<!--    {% load static %}-->
<!--    <link href="static/styles.css" rel="stylesheet">-->
</head>
<body>
<form action="{% url 'superheroes:create_new_superhero' %}" method="post">
    {% csrf_token %}
    <div>
        <label for="superhero_name" class="form-label">Superhero Name</label>
        <input type="text" class="form-control" id="superhero_name">
    </div>
    <div>
        <label for="alter_ego" class="form-label">Alter Ego</label>
        <input type="text" class="form-control" id="alter_ego">
    </div>
    <div>
        <label for="primary_ability" class="form-label">Primary Ability</label>
        <input type="text" class="form-control" id="primary_ability">
    </div>
    <div>
        <label for="secondary_ability" class="form-label">Secondary Ability</label>
        <input type="text" class="form-control" id="secondary_ability">
    </div>
    <div>
        <label for="catchphrase" class="form-label">Catchphrase</label>
        <input type="text" class="form-control" id="catchphrase">
    </div><br>
    <input type="submit" class="btn btn-primary center" value="Add new!"><br><br>
    <a href="{% url 'superheroes:index' %}">Go Back</a>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
</form>
</body>
</html>

superhero_database/superheroes/templates/superheroes/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Superhero Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link href="{% static 'css/"
</head>
<body>
<h1>Superhero Details</h1>
<ul>
    <div class="alert alert-primary">
    <b>Hero Name:</b> {{single_superhero.superhero_name}}<br>
    <b>Alter Ego:</b> {{single_superhero.alter_ego}}<br>
    <b>Primary Ability:</b> {{single_superhero.primary_ability}}<br>
    <b>Secondary Ability:</b> {{single_superhero.secondary_ability}}<br>
    <b>Catchphrase:</b> {{single_superhero.catchphrase}}<br><br>
    </div>
    <a href="{% url 'superheroes:index' %}">Go Back</a>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
</ul>
</body>
</html>

superhero_database/superheroes/templates/superheroes/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Superhero Index</title>
</head>
<body>
<img style="display: block; margin-left: auto; margin-right: auto; width: 50%;" src="https://i.cdn.newsbytesapp.com/images/l176_11011553006253.jpg" alt="superman">
<h1>List of superheroes!</h1>
<a href="{% url 'superheroes:create_new_superhero' %}">Create New Superhero</a>
<ul>
    {% for superhero in all_superheroes %}
    <li><h2> {{superhero.superhero_name}} </h2></li>
    <a href="{% url 'superheroes:detail' superhero.id %}">More info</a><br><br>
    <a href="{% url 'superheroes:update_superhero' superhero.id %}">Update Information</a><br><br>
    <form action="{% url 'superheroes:delete_superhero' superhero.id %}" name="delete_superhero">
        <button type="submit">Delete</button>
    </form>
    {% endfor %}
</ul>
</body>
</html>

superhero_database/superheroes/templates/superheroes/update.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Update Superhero</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
</head>
<body>
<form action="{% url 'superheroes:update_superhero' superhero.id %}" method="post">
    {% csrf_token %}
    <div>
        <label for="superhero_name" class="form-label">Superhero Name</label>
        <input type="text" class="form-control" id="superhero_name">
    </div>
    <div>
        <label for="alter_ego" class="form-label">Alter Ego</label>
        <input type="text" class="form-control" id="alter_ego">
    </div>
    <div>
        <label for="primary_ability" class="form-label">Primary Ability</label>
        <input type="text" class="form-control" id="primary_ability">
    </div>
    <div>
        <label for="secondary_ability" class="form-label">Secondary Ability</label>
        <input type="text" class="form-control" id="secondary_ability">
    </div>
    <div>
        <label for="catchphrase" class="form-label">Catchphrase</label>
        <input type="text" class="form-control" id="catchphrase">
    </div><br>


<!--    Superhero Name:<input type="text" name="superhero_name" id="superhero_name"><br>-->
<!--    Alter Ego:<input type="text" name="alter_ego" id="alter_ego"><br>-->
<!--    Primary Ability:<input type="text" name="primary_ability" id="primary_ability"><br>-->
<!--    Secondary Ability:<input type="text" name="secondary_ability" id="secondary_ability"><br>-->
<!--    Catchphrase:<input type="text" name="catchphrase" id="catchphrase"><br><br>-->
    <input type="submit" class="btn btn-primary" value="Update info!"><br><br>
    <a href="{% url 'superheroes:index' %}">Go Back</a>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
</form>
</body>
</html>